---
name: Kocom Wallpad with RS485 for 덕계역금강펜트리움
version: 2025.01.013
slug: kocom_py
description: Kocom Wallpad RS485 integration for Home Assistant - Updated for HA 2025.x by robert
stage: stable
auto_update: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/Hyunki6040/kocom.py
startup: application
boot: auto
uart: true
host_network: false
discovery:
  - mqtt
services:
  - mqtt:need
map:
  - share:rw
  - config:ro
options:
  rs485_type: "socket"
  socket_server: "192.168.0.222"
  socket_port: 8899
  serial_port: "/dev/ttyUSB0"
  mqtt_server: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "hk"
  mqtt_password: "hk0129"
  mqtt_allow_anonymous: false
  elevator_floor: 15
  init_temp: 23
  debug_mode: false
schema:
  rs485_type: list(serial|socket)
  socket_server: str?
  socket_port: "int(1,65535)?"
  serial_port: str?
  mqtt_server: str
  mqtt_port: "int(1,65535)"
  mqtt_username: str?
  mqtt_password: password?
  mqtt_allow_anonymous: bool
  elevator_floor: "int(1,50)?"
  init_temp: "int(15,30)?"
  debug_mode: bool
init: false
