---
name: Kocom Wallpad with RS485 for 덕계역금강펜트리움
version: 2025.01.004
slug: kocom_py
description: Kocom Wallpad RS485 integration for Home Assistant - Updated for HA 2025.x by robert
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/Hyunki6040/kocom.py
startup: application
boot: auto
uart: true
host_network: false
discovery:
  - mqtt
services:
  - mqtt:need
map:
  - share:rw
  - config:ro
options:
  mqtt_server: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  rs485_type: "serial"
  serial_port: "/dev/ttyUSB0"
  socket_server: ""
  socket_port: 8899
  debug_mode: false
schema:
  mqtt_server: str
  mqtt_port: "int(1,65535)"
  mqtt_username: str?
  mqtt_password: str?
  rs485_type: list(serial|socket)
  serial_port: str?
  socket_server: str?
  socket_port: "int(1,65535)?"
  debug_mode: bool
init: false
