name: Release Add-on

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from config.yaml
        id: version
        run: |
          VERSION=$(grep "^version:" config.yaml | cut -d' ' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Kocom Wallpad RS485 Add-on v${{ steps.version.outputs.version }}
            
            ### Auto-update now available!
            Enable auto-update in your add-on configuration to automatically receive updates.
            
            ### Changes
            - Check commit history for detailed changes
            
            ### Installation
            Add this repository to your Home Assistant:
            ```
            https://github.com/Hyunki6040/kocom.py
            ```
          draft: false
          prerelease: false

      - name: Update repository.json
        run: |
          VERSION=${{ steps.version.outputs.version }}
          echo "Updating repository.json with version $VERSION"
          
      - name: Commit version bump
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update version tracking"
          git push || true